CREATE TABLE CAD_PRODUTOS(
    CODIGO      BIGINT,
    NOME    VARCHAR(255),
    VALOR   DECIMAL(12,3),
    PRIMARY KEY(CODIGO)
);
CREATE SEQUENCE SEQ_CAD_PRODUTO AS BIGINT MINVALUE 1 START WITH 1 INCREMENT BY 1;
